language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$Home/.m2/repository'
    - '$Home/.gradle'

script:
  - "chmod +x ./aws-spring-book/gradlew"
  - "cd aws-spring-book"
  - "./gradlew clean build"

before_deploy:
  - zip -r Java-Spring/aws-spring-book *
  - mkdir -p deploy
  - mv Java-Spring/aws-spring-book.zip deploy/aws-spring-book.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: awspringbook-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - "kwakdh25@gmail.com"